version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH
      - HUGGINGFACE_TOKEN
      - MODEL_NAME
      - ORT_MODEL_NAME
    ports:
      - 31416:31416
  web:
    build:
      context: ./redago_web
      dockerfile: Dockerfile
    ports:
      - 80:80