version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=
      - HUGGINGFACE_TOKEN=
      - MODEL_NAME=
    ports:
      - 8000:8000
  web:
    build:
      context: ./redago_web
      dockerfile: Dockerfile
    ports:
      - 80:80